{
  "name": "Checks",
  "on": ["push"],
  "jobs":
    {
      "formatting":
        {
          "name": "Check formatting",
          "runs-on": "ubuntu-latest",
          "steps":
            [
              { "uses": "actions/checkout@v3" },
              { "uses": "Swatinem/rust-cache@v2" },
              {
                "name": "Set up toolchain",
                "run": "rustup toolchain install nightly --component rustfmt",
              },
              {
                "name": "Check formatting",
                "run": "cargo +nightly fmt -- --check",
              },
            ],
        },
      "clippy":
        {
          "name": "Clippy",
          "runs-on": "ubuntu-latest",
          "steps":
            [
              { "uses": "actions/checkout@v3" },
              { "uses": "Swatinem/rust-cache@v2" },
              {
                "name": "Set up toolchain",
                "run": "rustup component add clippy",
              },
              { "name": "Clippy", "run": "cargo clippy -- -Dwarnings" },
            ],
        },
      "tests":
        {
          "name": "Run tests",
          "runs-on": "ubuntu-latest",
          "steps":
            [
              { "uses": "actions/checkout@v3" },
              { "uses": "Swatinem/rust-cache@v2" },
              { "name": "Run tests", "run": "cargo test" },
            ],
        },
    },
}
